
rvm:
  - 2.4

env:
  - DB=postgresql

before_script:
  - psql -c 'create database edocmantest' -U postgres

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake spec

bundler_args: --binstubs=./bundler_stubs

after_success:
  - coveralls